# Generated by Django 4.1.1 on 2022-09-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('price', models.IntegerField()),
                ('des', models.TextField(default='')),
                ('images', models.ImageField(blank=True, default='', upload_to='pro_img')),
                ('date', models.DateField(auto_now_add=True)),
                ('Category', models.ManyToManyField(to='app1.category')),
                ('Sub_Category', models.ManyToManyField(to='app1.sub_category')),
            ],
        ),
    ]
